apiVersion: v1
kind: Secret
metadata:
  name: cinemaplex-secrets
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "your-aws-access-key"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret-key"
  S3_BUCKET_NAME: "cinemaplex-videos"
  MONGODB_URI: "mongodb://mongodb:27017/cinemaplex"
  REDIS_PASSWORD: "cinemaplex-redis-pass"
